=== jwilkie/web-serveur/model/section.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Section",
    "description": "A section of the material in notes website.",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "The schema used by this object.",
            "type": "string"
        },
        "title": {
            "description": "The title of this material section.",
            "type": "string"
        },
        "description": {
            "description": "The description of this material section.",
            "type": "string"
        },
        "pages": {
            "description": "All the pages in their specific order in the material section.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "disabled": {
            "description": "A value indicating whether this material section is disabled or not.",
            "type": "boolean"
        }
    },
    "required": ["title", "description"],
    "additionalProperties": false
}

=== jwilkie/web-serveur/app/(section)/module-11/section.json
{
    "title": "Manipulation avancée du DOM",
    "description": "Démonstration de la manipulation plus complexe du DOM avec javascript afin d'insérer, modifier ou supprimer des éléments, des propriétés ou des évènements dans le HTML de vos projets Web. Nous verrons aussi les impacts de ces manipulations sur la performance de vos pages Web.",
    "disabled": true,
    "pages": [

    ]
}

=== jwilkie/web-serveur/app/(section)/module-3/section.json
{
    "$schema": "../../../model/section.schema.json",
    "title": "Protocole HTTP",
    "description": "Introduction au protocole HTTP, aux API REST et aux données en format JSON. Démonstration de programmation de routes et d'utilisation de route statique sur Express.js.",
    "disabled": true,
    "pages": [

    ]
}

=== jwilkie/web-serveur/app/(section)/module-4/section.json
{
    "$schema": "../../../model/section.schema.json",
    "title": "Client et serveur",
    "description": "Introduction à la création d'interfaces graphiques clientes qui pourront communiquer avec les serveurs web à l'aide de requêtes et de réponses.",
    "disabled": false,
    "pages": [
        "introduction",
        "fetch-intro",
        "fetch-envoyer",
        "fetch-recevoir",
        "erreurs-communes",
        "deboguer-client",
        "deboguer-serveur",
        "lab-liste-taches",
        "lab-bibliotheque"
    ]
}

=== jwilkie/web-serveur/app/(section)/module-9/section.json
{
    "$schema": "../../../model/section.schema.json",
    "title": "Communication bidirectionnelle",
    "description": "Présentation des différents types de communication entre un client et un serveur avec le protocole HTTP et de l'utilisation de technologie pour permettre la communication bidirectionnelle.",
    "disabled": true,
    "pages": [

    ]
}
